src/1CW_Site/1CW_Site/1CW_Site/Controllers/ONGController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _1CW_Site.ActionResults;
using _1CW_Site.Models;
using OCW.BL;
using OCW.DAL.DTOs;
using OCW.DAL.Exceptions;

namespace _1CW_Site.Controllers
{
    public class ONGController : Controller
    {
        private readonly OCWBusinessLayer businessLayer;

        private const int IMAGE_MAX_WIDTH = 200;

        public ONGController(OCWBusinessLayer businessLayer)
        {
            this.businessLayer = businessLayer;
        }

        [HttpGet]
        public ActionResult ShowOrganizationImage(int id)
        {
            Organization o;
            try
            {
                o = businessLayer.GetOrganization(id);
            }
            catch (RecordNotFoundException<int>)
            {
                return null;
            }

            byte[] imageArray = o.Image;

            if (imageArray == null || imageArray.Length == 0)
            {
                string file = AppDomain.CurrentDomain.BaseDirectory + "Content\\Images\\charity.png";
                Image image = Image.FromFile(file);
                MemoryStream ms = new MemoryStream();
                image.Save(ms, ImageFormat.Png);
                imageArray = ms.ToArray();
            }
            return new ImageResult(imageArray, @"image/png");
        }

        // GET: /ONG/Details

        public ActionResult Details()
        {
            string userEmail = User.Identity.Name;
            Organization o = businessLayer.GetOrganizationFullInfo(userEmail);

            return View(new ONGModel
                            {
                                Address1 = o.Address.Address1,
                                Address2 = o.Address.Address2,
                                City = o.Address.City,
                                CountryName = o.Address.Country.Name,
                                Email = userEmail,
                                Name = o.Name,
                                PostalCode = o.Address.PostalCode,
                                Url = o.Url,
                                Tags = o.Tag.Select(t => t.Name),
                                Id = o.Id
                            });
        }

        //
        // GET: /ONG/Create

        public ActionResult Create()
        {
            IEnumerable<Country> countries = businessLayer.GetAllCountries();
            Dictionary<int, string> countriesDictionary = new Dictionary<int, string>(countries.Count());
            foreach (Country country in countries)
                countriesDictionary.Add(country.Id, country.Name);

            ViewBag.Countries = countriesDictionary;

            IEnumerable<Tag> tags = businessLayer.GetAllTags();
            Dictionary<int, string> tagsDictionary = new Dictionary<int, string>(tags.Count());
            foreach (Tag type in tags)
                tagsDictionary.Add(type.Id, type.Name);

            ViewBag.Tags = tagsDictionary;
            
            return View();
        } 

        //
        // POST: /ONG/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                byte[] tempImage;

                HttpPostedFileBase file = Request.Files["OngImage"];
                if (file != null)
                {
                    Image img = Image.FromStream(file.InputStream);

                    int width = img.Width;
                    int height = img.Height;
                    
                    if(width > IMAGE_MAX_WIDTH)
                    {
                        width = IMAGE_MAX_WIDTH;
                        height = (int)((float)height * width / img.Width);
                    }
                    img = img.GetThumbnailImage(width, height, null, IntPtr.Zero);

                    MemoryStream ms = new MemoryStream();
                    img.Save(ms, ImageFormat.Png);
                    tempImage = ms.ToArray();
                }
                else
                {
                    tempImage = new byte[] { };
                }

                List<int> tags = new List<int>();

                if (Request.Form.GetValues("tags") != null)

                    foreach (var tag in Request.Form.GetValues("tags"))
                    {
                        int tagId;
                        int.TryParse(tag, out tagId);
                        tags.Add(tagId);
                    }

                businessLayer.CreateOrganization(
                    collection["Name"],
                    collection["Url"],
                    tempImage,
                    collection["Email"],
                    collection["Password"],
                    collection["address1"],
                    collection["address2"],
                    collection["Postalcode"],
                    collection["City"],
                    int.Parse(collection["Country"]),
                    tags);

                return RedirectToAction("LogOn", "Account");
            }
            catch(Exception e)
            {
                return View();
            }
        }
        
        //
        // GET: /ONG/Edit
 
        public ActionResult Edit()
        {
            string userEmail = User.Identity.Name;
            Organization o = businessLayer.GetOrganizationFullInfo(userEmail);

            IEnumerable<Country> countries = businessLayer.GetAllCountries();
            Dictionary<int, string> countriesDictionary = new Dictionary<int, string>(countries.Count());
            foreach (Country country in countries)
                countriesDictionary.Add(country.Id, country.Name);

            ViewBag.Countries = countriesDictionary;

            IEnumerable<Tag> tags = businessLayer.GetAllTags();
            Dictionary<int, string> tagsDictionary = new Dictionary<int, string>(tags.Count());
            foreach (Tag type in tags)
                tagsDictionary.Add(type.Id, type.Name);

            ViewBag.Tags = tagsDictionary;

            return View(new ONGModel
            {
                Name = o.Name,
                Address1 = o.Address.Address1,
                Address2 = o.Address.Address2,
                City = o.Address.City,
                CountryId = o.Address.Country_id,
                Email = o.Email,
                Url = o.Url,
                PostalCode = o.Address.PostalCode,
                TagsIds = o.Tag.Select(tag => tag.Id)
            });
        }

        //
        // POST: /ONG/Edit

        [HttpPost]
        [Authorize]
        public ActionResult Edit(ONGModel model)
        {
            try
            {
                byte[] tempImage = null;

                HttpPostedFileBase file = Request.Files["OngImage"];
                if (file != null)
                {
                    Image img = Image.FromStream(file.InputStream);

                    int width = img.Width;
                    int height = img.Height;

                    if (width > IMAGE_MAX_WIDTH)
                    {
                        width = IMAGE_MAX_WIDTH;
                        height = (int)((float)height * width / img.Width);
                    }
                    img = img.GetThumbnailImage(width, height, null, IntPtr.Zero);

                    MemoryStream ms = new MemoryStream();
                    img.Save(ms, ImageFormat.Png);
                    tempImage = ms.ToArray();
                }

                List<int> tags = new List<int>();
                string[] tagsCheckBoxes;
                if ((tagsCheckBoxes = Request.Form.GetValues("tags")) != null)

                    foreach (var tag in tagsCheckBoxes)
                    {
                        int tagId;
                        int.TryParse(tag, out tagId);
                        tags.Add(tagId);
                    }

                string userEmail = User.Identity.Name;

                int userId = businessLayer.GetProfile(userEmail).Id;

                businessLayer.EditOrganization(userId, model.Name, model.Url, tempImage, model.Email, model.Address1, model.Address2,
                                             model.PostalCode, model.City, model.CountryId, tags);

                return RedirectToAction("Details");
            }
            catch (Exception e)
            {
                return View();
            }
        }

    }
}

src/1CW_Site/1CW_Site/1CW_Site/Views/ONG/Create.cshtml
@model _1CW_Site.Models.ONGModel

@{
    ViewBag.Title = "Register an ONG";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "ONG", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="fieldset">
        <div>Register ONG</div>
        <fieldset>
            <legend>ONG Information</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Password)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ConfirmPassword)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ConfirmPassword)
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Address1)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address1)
                @Html.ValidationMessageFor(model => model.Address1)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Address2)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address2)
                @Html.ValidationMessageFor(model => model.Address2)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.PostalCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PostalCode)
                @Html.ValidationMessageFor(model => model.PostalCode)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.City)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Country)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Country, new SelectList(ViewBag.Countries,"Key","Value"))
                @Html.ValidationMessageFor(model => model.Country)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Url)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Tags)
            </div>
            <div class="editor-field">
            @{
                foreach (KeyValuePair<int,string> tag in ViewBag.Tags)
                {
                    <input type="checkbox" name="tags" value="@tag.Key.ToString()" />
                    <label> @tag.Value </label>
                    <p />
                }
            }
            @Html.ValidationMessageFor(model => model.Tags)
            </div>

            <div class="editor-label">
                Image
            </div>
            <div class="editor-field">
                <input type="file" id="OngImage" name="OngImage" />
            </div>

            <p>
                <input type="submit" value="Register" />
            </p>
        </fieldset>
    </div>
}

src/1CW_Site/1CW_Site/1CW_Site/Views/ONG/Delete.cshtml
@model _1CW_Site.Models.ONGModel

@{
    ViewBag.Title = "Delete ONG";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ONGModels</legend>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">Email</div>
    <div class="display-field">@Model.Email</div>

    <div class="display-label">Type</div>
    <div class="display-field">@Model.Type</div>

    <div class="display-label">Address</div>
    <div class="display-field">@Model.Address</div>

    <div class="display-label">Password</div>
    <div class="display-field">@Model.Password</div>

    <div class="display-label">ConfirmPassword</div>
    <div class="display-field">@Model.ConfirmPassword</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

src/1CW_Site/1CW_Site/1CW_Site/Views/ONG/Details.cshtml
@model _1CW_Site.Models.ONGModel

@{
    ViewBag.Title = "My Profile Info";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<link href="@Url.Content("~/Content/Options.css")" rel="stylesheet" type="text/css" />

<div class="box" id="box_profile_info">
    <div class="box_title">Profile Info</div>
    <div class="box_content">
        <table>
            <tr>
                <td>Name: </td>
                <td>@Model.Name</td>
            </tr>
            <tr>
                <td>Email: </td>
                <td>@Model.Email</td>
            </tr>
            <tr>
                <td>Address1 :</td>
                <td>@Model.Address1</td>
            </tr>
            <tr>
                <td>Address2 :</td>
                <td>@Model.Address2</td>
            </tr>
            <tr>
                <td>City :</td>
                <td>@Model.City</td>
            </tr>
            <tr>
                <td>Country :</td>
                <td>@Model.CountryName</td>
            </tr>
            <tr>
                <td>Url: </td>
                <td>@Model.Url</td>
            </tr>
            <tr>
                <td>Image: </td>
                <td><img alt="Loaging Organization Image" src="@Url.Action("ShowOrganizationImage", "ONG", new { id = Model.Id })" /></td>
            </tr>
            <tr>
                <td>Tags: </td>
                <td>
                    @foreach (var item in Model.Tags)
                    {
                        @item <br />
                    }
                </td>
            </tr>
        </table>
    </div>
    <div>
        <p>
            @Html.ActionLink("Edit", "Edit") |
            @Html.ActionLink("Change Password", "ChangePassword", "Account") |
            @Html.ActionLink("Back to Home", "MyAccount", "Home")
        </p>
    </div>
</div>

src/1CW_Site/1CW_Site/1CW_Site/Views/ONG/Edit.cshtml
@model _1CW_Site.Models.ONGModel

@{
    ViewBag.Title = "Edit Profile";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "ONG", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.ValidationSummary(true)
    <div class="fieldset">
        <fieldset>
            <legend>Edit ONG</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Address1)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address1)
                @Html.ValidationMessageFor(model => model.Address1)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Address2)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Address2)
                @Html.ValidationMessageFor(model => model.Address2)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.PostalCode)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PostalCode)
                @Html.ValidationMessageFor(model => model.PostalCode)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.City)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Country)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.CountryId, new SelectList(ViewBag.Countries,"Key","Value"))
                @Html.ValidationMessageFor(model => model.Country)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Url)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Tags)
            </div>
            <div class="editor-field">
            @{
                foreach (KeyValuePair<int,string> tag in ViewBag.Tags)
                {
                    <input type="checkbox" name="tags" value="@tag.Key.ToString()" @(Model.TagsIds.Where(where => where == tag.Key).Count() > 0 ? "checked" : "") />
                    <label> @tag.Value </label>
                    <p />
                }
            }
            @Html.ValidationMessageFor(model => model.Tags)
            </div>
            <div class="editor-label">
                Image
            </div>
            <div class="editor-field">
                <input type="file" id="OngImage" name="OngImage" />
            </div>
            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
        <div>
            @Html.ActionLink("Back to Details", "Details")
        </div>
    </div>
}