src/1CW_Site/1CW_Site/1CW_Site/Controllers/EmergencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _1CW_Site.ActionResults;
using _1CW_Site.Models;
using OCW.BL;
using OCW.DAL.DTOs;
using OCW.DAL.Exceptions;
using OCW.DAL.IndependentLayerEntities;

namespace _1CW_Site.Controllers
{
    public class EmergencyController : Controller
    {
        private readonly OCWBusinessLayer businessLayer;

        public EmergencyController(OCWBusinessLayer businessLayer)
        {
            this.businessLayer = businessLayer;
        }

        //
        // GET: /Emergency/

        [Authorize]
        [HttpGet]
        public ActionResult List(int page)
        {
            return View(businessLayer.GetEmergencyWithOrganization(10, page).Select(model => new EmergencyModel()
                                                                                {
                                                                                    Title = model.Title,
                                                                                    Description = model.Description,
                                                                                    StartDate = model.StartDate,
                                                                                    EndDate = model.EndDate,
                                                                                    Weight = model.Weight,
                                                                                    OrganizationName = model.Organization.Name,
                                                                                    Id = model.Id
                                                                                })
                );
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            IEnumerable<IndependentOrganization> organizations = businessLayer.ListAllOrganizationsIndependentEntities();
            Dictionary<int, string> organizationsDictionary = new Dictionary<int, string>(organizations.Count());
            foreach (IndependentOrganization io in organizations)
            {
                organizationsDictionary.Add(io.Id, io.Name);
            }

            ViewBag.Organizations = organizationsDictionary;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(EmergencyModel model)
        {
            try
            {
                byte[] tempImage;

                HttpPostedFileBase file = Request.Files["Image"];
                if (file != null)
                {
                    Int32 length = file.ContentLength;
                    tempImage = new byte[length];
                    file.InputStream.Read(tempImage, 0, length);
                }
                else
                {
                    tempImage = new byte[] { };
                }

                businessLayer.CreateEmergency(model.Title, model.Description, model.StartDate, model.EndDate,
                                              model.Weight, tempImage, model.Organization);

                return RedirectToAction("List", new { page = 1});
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Emergency e = businessLayer.GetEmergency(id);

            IEnumerable<Organization> organizations = businessLayer.GetAllOrganizations();
            Dictionary<int, string> organizationsDictionary = new Dictionary<int, string>(organizations.Count());
            foreach (Organization io in organizations)
            {
                organizationsDictionary.Add(io.Id, io.Name);
            }

            ViewBag.Organizations = organizationsDictionary;

            return View(new EmergencyModel
                            {
                                Id = e.Id,
                                Title = e.Title,
                                Description = e.Description,
                                StartDate = e.StartDate,
                                EndDate = e.EndDate,
                                Weight = e.Weight,
                                Organization = e.Organization_id,
                            });
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(EmergencyModel model)
        {
            try
            {
                byte[] tempImage;

                HttpPostedFileBase file = Request.Files["Image"];
                if (file != null)
                {
                    Int32 length = file.ContentLength;
                    tempImage = new byte[length];
                    file.InputStream.Read(tempImage, 0, length);
                }
                else
                {
                    tempImage = null;
                }

                businessLayer.EditEmergency(model.Id, model.Title, model.Description, model.StartDate, model.EndDate,
                                              model.Weight, tempImage, model.Organization);

                return RedirectToAction("List", new { page = 1 });
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            businessLayer.DeleteEmergency(id);

            return RedirectToAction("List", new { page = 1 });
        }

        public ActionResult Active()
        {
            IEnumerable<Emergency> emergencies = businessLayer.GetActiveEmergencies();

            return PartialView(emergencies.Select(o => new EmergencyModel
                                                    {
                                                        Description = o.Description,
                                                        EndDate = o.EndDate,
                                                        Organization = o.Organization_id,
                                                        StartDate = o.StartDate,
                                                        Title = o.Title,
                                                        Weight = o.Weight,
                                                        Id= o.Id,
                                                        HasImage = o.Image != null && o.Image.Length > 0
                                                    }));
        }

        [HttpGet]
        public ActionResult ShowImage(int id)
        {
            Emergency e;
            try
            {
                e = businessLayer.GetEmergency(id);
            }
            catch (RecordNotFoundException<int>)
            {
                return null;
            }
            return new ImageResult(e.Image, @"image/png");
        }
    }
}

src/1CW_Site/1CW_Site/1CW_Site/Views/Emergency/Active.cshtml
@model IEnumerable<_1CW_Site.Models.EmergencyModel>

@if (Model.Count() > 0)
{
    foreach (var emergency in Model)
    {
        <div class="box box_emergency">
            <div class="box_title"><img src="../../Content/Images/siren.gif" alt="Siren" />&nbsp;Emergency - @emergency.Title&nbsp;<img src="../../Content/Images/siren.gif" alt="Siren" /></div>
            <div class="box_content">
                @if (emergency.HasImage)
                {
                    <img src="@string.Format("/Emergency/ShowImage/{0}", emergency.Id)" alt="@emergency.Title" /><br />
                }
                <p>
                    @emergency.Description
                </p>
            </div>
        </div>
    }
}

src/1CW_Site/1CW_Site/1CW_Site/Views/Emergency/Create.cshtml
@model _1CW_Site.Models.EmergencyModel

@{
    ViewBag.Title = "Create Emergency";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div class="fieldset">
        <fieldset>
            <legend>Create Emergency</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.StartDate)
            </div>
            <div class="editor-field">
                @Html.TextBox("StartDate", string.Format("{0:yyyy-MM-dd}", "yyyy-mm-dd"))
               @* @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)*@
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.EndDate)
            </div>
            <div class="editor-field" id="EndDateField" >
               @Html.TextBox("EndDate", string.Format("{0:yyyy-MM-dd}", "yyyy-mm-dd"))
         @*      @{
        try
        {
            DateTime dt = DateTime.Parse(Context.Items["EndDataField"].ToString());

        }
        catch (Exception)
        {
                        <p>coiso</p>
        }
    }*@
              @*  @Html.ValidationMessage("EndDate",DateTime.Parse("EndDate"),)*@
                 @*@Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)*@
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Organization)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Organization, new SelectList(ViewBag.Organizations, "Key", "Value"))
                @Html.ValidationMessageFor(model => model.Organization)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Weight)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Weight)
                @Html.ValidationMessageFor(model => model.Weight)
            </div>

            <div class="editor-field">
                <input type="file" id="Image" name="Image" />
            </div>

            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
        <div>
        @Html.ActionLink("Back to List", "List", "Emergency", new { page = 1 }, null)
    </div>
    </div>
}

src/1CW_Site/1CW_Site/1CW_Site/Views/Emergency/Delete.cshtml
@model _1CW_Site.Models.EmergencyModel

@{
    ViewBag.Title = "Delete Emergency";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>EmergencyModel</legend>

    <table>
    <tr>
        <th></th>
        <th>
            Title
        </th>
        <th>
            Description
        </th>
        <th>
            StartDate
        </th>
        <th>
            Weight
        </th>
        <th>
            EndDate
        </th>
        <th>
            Organization_id
        </th>
    </tr>
    @foreach (var item in ViewBag.Emergencies)
{
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
        <td>
            @item.Title
        </td>
        <td>
            @item.Description
        </td>
        <td>
            @String.Format("{0:g}", item.StartDate)
        </td>
        <td>
            @String.Format("{0:F}", item.Weight)
        </td>
        <td>
            @String.Format("{0:g}", item.EndDate)
        </td>
        <td>
            @item.Organization_id
        </td>
    </tr>
}

</table>
    @*<div class="display-label">Title</div>
    <div class="display-field">@Model.Title</div>

    <div class="display-label">Description</div>
    <div class="display-field">@Model.Description</div>

    <div class="display-label">StartDate</div>
    <div class="display-field">@String.Format("{0:g}", Model.StartDate)</div>

    <div class="display-label">EndDate</div>
    <div class="display-field">@String.Format("{0:g}", Model.EndDate)</div>

    <div class="display-label">Weight</div>
    <div class="display-field">@String.Format("{0:F}", Model.Weight)</div>

    <div class="display-label">Organization</div>
    <div class="display-field">@Model.Organization</div>*@
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index", "Emergency", new { page = 1 }, null)
    </p>
}

src/1CW_Site/1CW_Site/1CW_Site/Views/Emergency/Edit.cshtml
@model _1CW_Site.Models.EmergencyModel

@{
    ViewBag.Title = "Edit Emergency";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <div class="fieldset">
        <fieldset>
            <legend>Edit Emergency</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.StartDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.EndDate)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Weight)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Weight)
                @Html.ValidationMessageFor(model => model.Weight)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Organization)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Organization, new SelectList(ViewBag.Organizations, "Key", "Value"))
                @Html.ValidationMessageFor(model => model.Organization)
            </div>

            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
        <div>
            @Html.ActionLink("Back to List", "List", new { page = 1 })
        </div>
    </div>
}

src/1CW_Site/1CW_Site/1CW_Site/Views/Emergency/List.cshtml
@model IEnumerable<_1CW_Site.Models.EmergencyModel>

@{
    ViewBag.Title = "Emergencies";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<link href="@Url.Content("~/Content/Emergency.css")" rel="stylesheet" type="text/css" />

<div class="box" id="box_emergency">
    <div>@Html.ActionLink("Create New", "Create")</div>
    <div class="box_title">Emergency</div>
    <div class="box_content">
        <table>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Description
                </th>
                <th>
                    StartDate
                </th>
                <th>
                    EndDate
                </th>
                <th>
                    Weight
                </th>
                <th>
                    Organization
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Description
                </td>
                <td>
                    @String.Format("{0:g}", item.StartDate)
                </td>
                <td>
                    @String.Format("{0:g}", item.EndDate)
                </td>
                <td>
                    @String.Format("{0:F}", item.Weight)
                </td>
                <td>
                    @item.OrganizationName
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>
            </tr>
        }

        </table>
    </div>
    <div>@Html.ActionLink("Create New", "Create")</div>
</div>


    