src/1CW_Site/1CW_Site/1CW_Site/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _1CW_Site.ActionResults;
using OCW.DAL.DTOs;
using _1CW_Site.Models;
using OCW.BL;
using OCW.DAL.Exceptions;

namespace _1CW_Site.Controllers
{
    public class CompanyController : Controller
    {
        //
        // GET: /Company/

        private readonly OCWBusinessLayer businessLayer;

        private const int IMAGE_MAX_WIDTH = 200;


        public CompanyController(OCWBusinessLayer businessLayer)
        {
            this.businessLayer = businessLayer;
        }

        public ActionResult ShowCompanyImage(int id)
        {
            Company c;
            try
            {
                 c = businessLayer.GetCompany(id);
            } catch(RecordNotFoundException<int>)
            {
                return null;
            }

            byte[] imageArray = c.Image;

            if (imageArray == null || imageArray.Length == 0)
            {
                string file = AppDomain.CurrentDomain.BaseDirectory + "Content\\Images\\ecommerce.png";
                Image image = Image.FromFile(file);
                MemoryStream ms = new MemoryStream();
                image.Save(ms, ImageFormat.Png);
                imageArray = ms.ToArray();
            }
            return new ImageResult(imageArray, @"image/png");
        }

        //
        // GET: /Company/Details/
        [Authorize]
        public ActionResult Details()
        {
            string userEmail = User.Identity.Name;
            Company c = businessLayer.GetCompanyFullInfo(userEmail);

            return View(new CompanyModel()
                {
                    Name = c.Name,
                    Address1 = c.Address.Address1,
                    Address2 = c.Address.Address2,
                    City = c.Address.City,
                    Country = c.Address.Country.Name,
                    CountryId = c.Address.Country_id,
                    Email = c.Email,
                    Url = c.Url,
                    PostalCode = c.Address.PostalCode,
                    Tags = c.Tag.Select(tag => tag.Name),
                    Id = c.Id
                });
        }

        //
        // GET: /Company/Create

        public ActionResult Create()
        {
            IEnumerable<Country> countries = businessLayer.GetAllCountries();
            Dictionary<int, string> countriesDictionary = new Dictionary<int, string>(countries.Count());
            foreach (Country country in countries)
                countriesDictionary.Add(country.Id, country.Name);

            ViewBag.Countries = countriesDictionary;

            IEnumerable<Tag> tags = businessLayer.GetAllTags();
            Dictionary<int, string> tagsDictionary = new Dictionary<int, string>(tags.Count());
            foreach (Tag type in tags)
                tagsDictionary.Add(type.Id, type.Name);

            ViewBag.Tags = tagsDictionary;

            return View();
        } 

        //
        // POST: /Company/Create

        [HttpPost]
        public ActionResult Create(CompanyModel model)
        {
            try
            {
                byte[] tempImage;
                
                HttpPostedFileBase file = Request.Files["CompanyImage"];
                if(file != null)
                {
                    Image img = Image.FromStream(file.InputStream);

                    int width = img.Width;
                    int height = img.Height;

                    if (width > IMAGE_MAX_WIDTH)
                    {
                        width = IMAGE_MAX_WIDTH;
                        height = (int)((float)height * width / img.Width);
                    }
                    img = img.GetThumbnailImage(width, height, null, IntPtr.Zero);

                    MemoryStream ms = new MemoryStream();
                    img.Save(ms, ImageFormat.Png);
                    tempImage = ms.ToArray();
                }
                else
                {
                    tempImage = new byte[]{};
                }

                List<int> tags = new List<int>();
                string[] tagsCheckBoxes;
                if ((tagsCheckBoxes = Request.Form.GetValues("tags")) != null)

                    foreach (var tag in tagsCheckBoxes)
                    {
                        int tagId;
                        int.TryParse(tag, out tagId);
                        tags.Add(tagId);
                    }

                businessLayer.CreateCompany(model.Name, model.Url, tempImage, model.Email, model.Password, model.Address1, model.Address2,
                                             model.PostalCode, model.City, model.CountryId, tags);

                return RedirectToAction("MyAccount", "Home");
            }
            catch
            {
                ViewBag.ListCountry = businessLayer.ListAllCountries();
                return View();
            }
        }
        
        //
        // GET: /Company/Edit
        [Authorize]
        public ActionResult Edit()
        {
            string userEmail = User.Identity.Name;
            Company c = businessLayer.GetCompanyFullInfo(userEmail);

            IEnumerable<Country> countries = businessLayer.GetAllCountries();
            Dictionary<int, string> countriesDictionary = new Dictionary<int, string>(countries.Count());
            foreach (Country country in countries)
                countriesDictionary.Add(country.Id, country.Name);

            ViewBag.Countries = countriesDictionary;

            IEnumerable<Tag> tags = businessLayer.GetAllTags();
            Dictionary<int, string> tagsDictionary = new Dictionary<int, string>(tags.Count());
            foreach (Tag type in tags)
                tagsDictionary.Add(type.Id, type.Name);

            ViewBag.Tags = tagsDictionary;

            return View(new CompanyModel
            {
                Name = c.Name,
                Address1 = c.Address.Address1,
                Address2 = c.Address.Address2,
                City = c.Address.City,
                CountryId = c.Address.Country_id,
                Email = c.Email,
                Url = c.Url,
                PostalCode = c.Address.PostalCode,
                TagsIds = c.Tag.Select(tag => tag.Id)
            });
        }

        //
        // POST: /Company/Edit

        [HttpPost]
        [Authorize]
        public ActionResult Edit(CompanyModel model)
        {
            try
            {
                byte[] tempImage = null;
                
                HttpPostedFileBase file = Request.Files["CompanyImage"];
                if(file != null)
                {
                    Image img = Image.FromStream(file.InputStream);

                    int width = img.Width;
                    int height = img.Height;

                    if (width > IMAGE_MAX_WIDTH)
                    {
                        width = IMAGE_MAX_WIDTH;
                        height = (int)((float)height * width / img.Width);
                    }
                    img = img.GetThumbnailImage(width, height, null, IntPtr.Zero);

                    MemoryStream ms = new MemoryStream();
                    img.Save(ms, ImageFormat.Png);
                    tempImage = ms.ToArray();
                }

                List<int> tags = new List<int>();
                string[] tagsCheckBoxes;
                if ((tagsCheckBoxes = Request.Form.GetValues("tags")) != null)

                    foreach (var tag in tagsCheckBoxes)
                    {
                        int tagId;
                        int.TryParse(tag, out tagId);
                        tags.Add(tagId);
                    }

                string userEmail = User.Identity.Name;

                int userId = businessLayer.GetProfile(userEmail).Id;

                businessLayer.EditCompany(userId, model.Name, model.Url, tempImage, model.Email, model.Address1, model.Address2,
                                             model.PostalCode, model.City, model.CountryId, tags);

                return RedirectToAction("Details");
            }
            catch(Exception e)
            {
                return View();
            }
        }

        //
        // GET: /Company/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            businessLayer.DeleteCompany(id);
            return View();
        }
    }
}

src/1CW_Site/1CW_Site/1CW_Site/Controllers/PersonController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using _1CW_Site.Models;
using OCW.BL;
using OCW.DAL.DTOs;

namespace _1CW_Site.Controllers
{
    public class PersonController : Controller
    {
        
        private readonly OCWBusinessLayer businessLayer;

        public PersonController(OCWBusinessLayer businessLayer)
        {
            this.businessLayer = businessLayer;
        }

        //
        // GET: /Profile/Details

        public ActionResult Details()
        {
            string name = HttpContext.User.Identity.Name;

            Person v = businessLayer.GetPersonFullInfo(name);

            return View(new PersonModel
                            {
                                Id = v.Id,
                                Address1 = v.Address.Address1,
                                Address2 = v.Address.Address2,
                                City = v.Address.City,
                                Country = v.Address.Country.Name,
                                PostalCode = v.Address.PostalCode,
                                Email = v.Email,
                                FirstName = v.FirstName,
                                LastName = v.LastName,
                                BirthDate = v.Birthdate
                            });
        }

        //
        // GET: /Profile/Create

        public ActionResult Create()
        {
            ViewBag.ListCountry = businessLayer.ListAllCountries();

            return View();
        } 

        //
        // POST: /Profile/Create

        [HttpPost]
        public ActionResult Create(PersonModel model)
        {
            try
            {
                businessLayer.CreatePerson(model.FirstName,model.LastName,model.Email,model.Password,
                    model.Address1,model.Address2,model.BirthDate,model.PostalCode,model.City, model.Country ,"user");

                IFormsAuthenticationService FormsService = new FormsAuthenticationService();
                FormsService.SignIn(model.Email, false);

                Response.Cookies["UserFullName"].Value = model.FirstName + " " + model.LastName;

                return RedirectToAction("MyAccount","Home");
            }
            catch
            {
                ModelState.AddModelError("", "ERROR");
                ViewBag.ListCountry = businessLayer.ListAllCountries();
                return View(model);
            }
        }
        
        //
        // GET: /Profile/Edit
 
        public ActionResult Edit()
        {
            IEnumerable<Country> countries = businessLayer.GetAllCountries();
            Dictionary<int, string> countriesDictionary = new Dictionary<int, string>(countries.Count());
            foreach (Country country in countries)
                countriesDictionary.Add(country.Id, country.Name);

            ViewBag.Countries = countriesDictionary;

            string email = HttpContext.User.Identity.Name;

            Person v = businessLayer.GetPersonFullInfo(email);

            return View(new PersonModel
            {
                Address1 = v.Address.Address1,
                Address2 = v.Address.Address2,
                CountryId = v.Address.Country_id,
                City = v.Address.City,
                Email = v.Email,
                FirstName = v.FirstName,
                LastName = v.LastName,
                RegisteredDate = v.RegisteredDate,
                PostalCode = v.Address.PostalCode
            });
        }

        //
        // POST: /Profile/Edit

        [HttpPost]
        public ActionResult Edit(PersonModel model)
        {
            try
            {
                string email = HttpContext.User.Identity.Name;

                int userId = businessLayer.GetProfile(email).Id;

                businessLayer.EditPerson(userId, model.FirstName, model.LastName, model.Email, model.Address1, model.Address2,
                                             model.PostalCode, model.City, model.CountryId, model.BirthDate);

                return RedirectToAction("Details");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/1CW_Site/1CW_Site/1CW_Site/Views/Shared/_LayoutCompany.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @*<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/Content/Start.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">
        <div id="headerContainer">
            <div id="headerContent">
                <div id="headerLogo" class="lfloat">
                    <img src="../../Content/Images/logo.png" id="headerLogo1" />
                    <span class="" style="text-align=center;vertical-align=middle;font-size:x-large;">
                        One Cent for the World
                    </span>
                </div>
                
            </div>
        </div>

        <div id="mainContainer">
            <div id="mainCenterContent">
                @RenderBody()
            </div>
            
            <div id="footer">
            </div>

        </div>
    </div>
</body>
</html>

src/1CW_Site/1CW_Site/1CW_Site/Views/Shared/_LayoutStart.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

@{
    var cookie =  this.Request.Cookies["ProfileType"];
    if(cookie != null)
    {
        ViewBag.ProfileType = cookie.Value;
    }else
    {
        ViewBag.ProfileType = string.Empty;
    }
    
}

<html>
<head>
    <title>OCW - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/LayoutUserProfile.css")" rel="stylesheet" type="text/css" />
    <!--[if IE]>
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/IE.css")" />
    <![endif]-->
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>  
    <div class="content">
        <div class="header">
            <div class="header_left">
                <img src="../../Content/Images/logo.png" alt="One Cent World" />
            </div>
            <div class="header_middle">
                <div class="header_logo_text">
                    <img src="../../Content/Images/one_cent_world_text.png" alt="One Cent World ...where every cent counts!" />
                    <div class="header_info">
                        @if(Request.IsAuthenticated) {
                            <text>Welcome <b>@Context.User.Identity.Name</b>!
                            <span class="log">[</span> @Html.ActionLink("Log Off", "LogOff", "Account") <span class="log">]</span></text>
                        } else {
                            @:<span class="log">[</span> @Html.ActionLink("Log On", "LogOn", "Account") <span class="log">]</span>
                        }
                        <p  class="centered_image">
                            <a href="http://www.endpoverty2015.org" target="_blank"><img src="../../Content/Images/end_poverty.png" alt="End Poverty 2015" /></a>
                        </p>
                    </div>
                </div>
                <div class="menu">
                    <div class="menu_left menu_register_person">
                        <div class="menu_right menu_register_person">
                            <div class="menu_middle menu_register_person">@Html.ActionLink("Register User","Create","Person")</div>
                        </div>
                    </div>
                    <div class="menu_left menu_register_company">
                        <div class="menu_right menu_register_company">
                            <div class="menu_middle menu_register_company">@Html.ActionLink("Register Company", "Create", "Company")</div>
                        </div>
                    </div>
                    <div class="menu_left menu_developers">
                        <div class="menu_right menu_developers">
                            <div class="menu_middle menu_developers">@Html.ActionLink("Developers", "Create", "Developers")</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            @{Html.RenderAction("Active", "Emergency");}
            <div class="main_content">
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="footer_content">
            <div class="footer_logo_text">
                <img src="../../Content/Images/one_cent_world_text_footer.png" alt="One Cent World ...changing the world in every cent!" />
            </div>
            <div class="footer_ic">
                <a href="http://www.imaginecup.com" target="_blank"><img src="../../Content/Images/imagine_cup_2011.png" alt="Imagine Cup 2011"/></a>
            </div>
            <div class="footer_copyright">
                <img src="../../Content/Images/copyright.png" alt="Copyright &copy; 2011 One Cent World" />
            </div>
        </div>
    </div>
</body>
</html>

src/1CW_Site/1CW_Site/1CW_Site/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

@{
    var cookie =  this.Request.Cookies["ProfileType"];
    if(cookie != null)
    {
        ViewBag.ProfileType = cookie.Value;
    }else
    {
        ViewBag.ProfileType = string.Empty;
    }
    
}

<html>
<head>
    <title>OCW - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/LayoutUserProfile.css")" rel="stylesheet" type="text/css" />
    <!--[if IE]>
        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/IE.css")" />
    <![endif]-->
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="content">
        <div class="header">
            <div class="header_left">
                <img src="../../Content/Images/logo.png" alt="One Cent World" />
            </div>
            <div class="header_middle">
                <div class="header_logo_text">
                    <img src="../../Content/Images/one_cent_world_text.png" alt="One Cent World ...where every cent counts!" />
                    <div class="header_info">
                        @if(Request.IsAuthenticated) {
                            <text>Welcome <b>@Context.User.Identity.Name</b>!
                            <span class="log">[</span> @Html.ActionLink("Log Off", "LogOff", "Account") <span class="log">]</span></text>
                        } else {
                            @:<span class="log">[</span> @Html.ActionLink("Log On", "LogOn", "Account") <span class="log">]</span>
                        }
                        <p  class="centered_image">
                            <a href="http://www.endpoverty2015.org" target="_blank"><img src="../../Content/Images/end_poverty.png" alt="End Poverty 2015" /></a>
                        </p>
                    </div>
                </div>
                <div class="menu">
                    <div class="menu_left menu_account">
                        <div class="menu_right menu_account">
                            <div class="menu_middle menu_account">@Html.ActionLink("My Account","MyAccount","Home")</div>
                        </div>
                    </div>
                    <div class="menu_left menu_deposit">
                        <div class="menu_right menu_deposit">
                            <div class="menu_middle menu_deposit">@Html.ActionLink("Deposit", "List", "Deposit", new { page = 1 }, null)</div>
                        </div>
                    </div>
                    <div class="menu_left menu_withdraw">
                        <div class="menu_right menu_withdraw">
                            <div class="menu_middle menu_withdraw">@Html.ActionLink("Withdraw", "List", "Withdraw", new { page = 1 }, null)</div>
                        </div>
                    </div>
                    <div class="menu_left menu_history">
                        <div class="menu_right menu_history">
                            <div class="menu_middle menu_history">@Html.ActionLink("History", "History", "Home", new { page = 1 }, null)</div>
                        </div>
                    </div>
                    <div class="menu_left menu_options">
                        <div class="menu_right menu_options">
                            <div class="menu_middle menu_options">@Html.ActionLink("Profile", "Details", (string)ViewBag.ProfileType)</div>
                        </div>
                    </div>
                    <div class="menu_left menu_about">
                        <div class="menu_right menu_about">
                            <div class="menu_middle menu_about">@Html.ActionLink("About Us", "About", "Home")</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            @{Html.RenderAction("Active", "Emergency");}
            <div class="main_content">
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="footer_content">
            <div class="footer_logo_text">
                <img src="../../Content/Images/one_cent_world_text_footer.png" alt="One Cent World ...changing the world in every cent!" />
            </div>
            <div class="footer_ic">
                <a href="http://www.imaginecup.com" target="_blank"><img src="../../Content/Images/imagine_cup_2011.png" alt="Imagine Cup 2011"/></a>
            </div>
            <div class="footer_copyright">
                <img src="../../Content/Images/copyright.png" alt="Copyright &copy; 2011 One Cent World" />
            </div>
        </div>
    </div>
</body>
</html>

src/1CW_Site/1CW_Site/1CW_Site/Views/Shared/_LayoutUserProfile.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/LayoutUserProfile.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="header">
        <div class="header_top">
            <div class="header_top_logo">
                <img src="../../Content/Images/logo.png" alt="no image" />
            </div>

            <div class="ocw_title"><img src="../../Content/Images/ocwWord.png" alt="no image" /></div>

            <div class="header_top_info"> Welcome, Diogo Machado! | Logout </div>

        </div> 
        <div class="header_menu">
            <div class="button_container">
                <div class="header_menu_button">@Html.ActionLink("My Account","MyAccountButton","Profile")</div>
                <div class="header_menu_button">@Html.ActionLink("Deposit","DepositButton","Profile")</div>
                <div class="header_menu_button">@Html.ActionLink("Withdraw","WithdrawButton","Profile")</div>
                <div class="header_menu_button">@Html.ActionLink("Send Money","SendMoneyButton","Profile")</div>
                <div class="header_menu_button">@Html.ActionLink("Options","OptionsButton","Profile")</div>
                <div class="header_menu_button">@Html.ActionLink("Statistics","StatisticsButton","Profile")</div>
            </div>
        </div>
    </div>
    <div class="main">
        <div class="main_content">
            @RenderBody()
        </div>

    </div>

    <div class="footer"></div>

</body>
</html>

src/1CW_Site/1CW_Site/1CW_Site/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}